spring.application.name=englishdaily
spring.ai.model.chat=openai
spring.ai.model.embedding=openai
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-validation=false
spring.threads.virtual.enabled=true
#socket io configuration
englishdaily.socketio.server.host=0.0.0.0
englishdaily.socketio.server.port=8878
englishdaily.socketio.server.context=/ask-llama/socket
#Llama Setup Chat
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.ollama.base-url=http://192.168.5.168:11434
#spring.ai.ollama.chat.model=deepseek-r1:8b
#spring.ai.ollama.chat.model=hf.co/bartowski/DeepSeek-R1-Distill-Llama-8B-GGUF:Q6_K
englishdaily.chat-service.llm-model=none
#OpenAI Setup Chat
#enable actuator
management.security.enabled=false
#kubernetes probes
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
# Liquibase
spring.liquibase.enabled=true
# Enable loggin advisor
englishdaily.logging-advisor.enabled=false
#RabbitMQ
spring.rabbitmq.host=rabbitmq.broker
spring.rabbitmq.username=rabbit
spring.rabbitmq.password=-
spring.rabbitmq.port=5672
spring.rabbitmq.vhost=/
rabbitmq.receiver.retry.initial-interval=120000
rabbitmq.receiver.retry.max-attempts=2
rabbitmq.receiver.retry.multiplier=2
rabbitmq.receiver.retry.max-interval=1000000
com.antoniomm.englishdaily.exchange-name=exchange.home.events
com.antoniomm.englishdaily.queue-name=englishdaily.home.events
com.antoniomm.englishdaily.dead-letter-exchange-name=dlx.englishdaily.home.events
com.antoniomm.englishdaily.vocabulary-lessons.max-size=5
# Google Drive Configuration
google.drive.credentials.path=service-account.json
google.drive.documents.folder-id=1QKftg6_RUCjCPujOgGDlkUn7hNxfvHG4
# Application name for Google Drive API
google.drive.application.name=English Daily
