spring.application.name=englishdaily
spring.ai.ollama.base-url=http://192.168.5.168:11434
#spring.ai.ollama.chat.model=deepseek-r1:8b
spring.ai.ollama.chat.model=hf.co/bartowski/DeepSeek-R1-Distill-Llama-8B-GGUF:Q6_K
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-validation=false
spring.threads.virtual.enabled=true
#socket io configuration
englishdaily.socketio.server.host=0.0.0.0
englishdaily.socketio.server.port=8878
englishdaily.socketio.server.context=/ask-llama/socket
englishdaily.chat-service.llm-model=deepseek
#enable actuator
management.security.enabled=false
#kubernetes probes
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
# Liquibase
spring.liquibase.enabled=true
# Enable loggin advisor
englishdaily.logging-advisor.enabled=false