### Populate vector store
POST http://controlplane.local/english-daily/api/v1/englishdaily/vector-store

### Get daily vocabulary
GET http://controlplane.local/english-daily/api/v1/englishdaily/vocabulary

### Ask llama
POST http://controlplane.local/english-daily/api/v1/englishdaily/ask-llama
Content-Type: application/json;charset=UTF-8

{
  "question": "Show me ten prhasal verbs related with family and relationships"
}

### Ask llama get
GET http://controlplane.local/english-daily/api/v1/englishdaily/ask-llama?question=what is the meaning of the idiom clock watcher

### get all Grammar Lesson
GET http://controlplane.local/english-daily/api/v1/englishdaily/grammar-lessons

### Grammar Lesson
GET http://controlplane.local/english-daily/api/v1/englishdaily/grammar?grammarLesson=CLEFT_SENTENCES


### Post Vocabulary lesson
POST http://controlplane.local/api/v1/englishdaily/grammar-lessons
Content-Type: application/json;charset=UTF-8

{
  "question": "Show me ten prhasal verbs related with family and relationships"
}
