apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pgvector
    role: db
  name: pgvector
  namespace: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: pgvector
status:
  loadBalancer: {}
